include(FetchContent)
fetchcontent_declare(
    ut
    GIT_REPOSITORY https://github.com/mccakit/ut-glaze
    GIT_TAG 9a23541475269ead9046d70e3583515bb91c5e7d
    GIT_SHALLOW TRUE)
set(UT_ENABLE_MODULES ON)
fetchcontent_makeavailable(ut)
find_package(Boost REQUIRED)
find_package(sqlite REQUIRED)
find_package(Eigen3 REQUIRED)

add_subdirectory(api_test)
add_subdirectory(beve_test)
add_subdirectory(bson_test)
add_subdirectory(cbor_test)
add_subdirectory(jsonb_test)
add_subdirectory(jsonb_sqlite_test)
add_subdirectory(buffer_pool_test)
add_subdirectory(cli_menu_test)
add_subdirectory(compare_test)
add_subdirectory(ordered_small_map_test)
add_subdirectory(ordered_map_test)
add_subdirectory(csv_test)
add_subdirectory(eigen_test)
add_subdirectory(example_json)
add_subdirectory(exceptions_test)
add_subdirectory(inplace_vector)
add_subdirectory(float_write_test)
if(glaze_BUILD_PERFORMANCE_TESTS)
    add_subdirectory(int_parsing)
endif()
add_subdirectory(jmespath)
if(NOT glaze_ENABLE_REFLECTION26)
    add_subdirectory(jsonrpc_test)
endif()
add_subdirectory(key_transformers_test)
#add_subdirectory(lib_test)
add_subdirectory(mock_json_test)
add_subdirectory(reflection)
add_subdirectory(roundtrip)
add_subdirectory(stencil)
add_subdirectory(threading_test)
add_subdirectory(toml_test)
add_subdirectory(utility_formats)
# # add_subdirectory(yaml_test)
# # add_subdirectory(yaml_conformance)
add_subdirectory(msgpack_test)
add_subdirectory(ostream_buffer_test)
add_subdirectory(istream_buffer_test)

if(glaze_SIMPLE_FLOAT_TEST)
    add_subdirectory(simple_float_test)
endif()

# JSON Tests
add_subdirectory(chrono_test)
add_subdirectory(json_conformance)
if(glaze_BUILD_PERFORMANCE_TESTS)
    add_subdirectory(json_performance)
endif()
add_subdirectory(json_reflection_test)
add_subdirectory(json_test)

# if(glaze_BUILD_NETWORKING_TESTS)
#     add_subdirectory(networking_tests)
# endif()

# if(glaze_EETF_FORMAT)
#     add_subdirectory(eetf_test)
# endif()

# if(glaze_ENABLE_REFLECTION26)
#     add_subdirectory(p2996_test)
# endif()
