add_executable(key_transformers_test)
target_sources(key_transformers_test PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/key_transformers_test.cpp)
target_link_libraries(key_transformers_test PRIVATE ut::ut glaze glaze::asio)
target_include_directories(key_transformers_test PRIVATE ${CMAKE_SOURCE_DIR}/modules)
add_test(NAME key_transformers_test COMMAND key_transformers_test)
